Noop on attempt to cancel non-running job
spotify/flink-on-k8s-operator pull request #431
Opened 2022-06-24 09:41 UTC by kassybas

In has finished or was already cancelled, the validation webhook rejects the cancellation attempt. This leads to any external system (ie. Flyte) attempting to continuously retrying the cancellation to reconcile its state.

2022-06-24 10:33 UTC, regadas requested changes
I believe that this should be handled on such external systems based on response status/error. We could perhaps have a more granular error here to distinguish those situations.

2022-06-27 13:12 UTC, regadas commented on apis/flinkcluster/v1beta1/flinkcluster_validate.go
> +				return errors.NewResourceExpired(fmt.Sprintf(InvalidJobStateForJobCancelMsg, ControlAnnotation))
dope!

2022-06-27 13:13 UTC, regadas approved these changes
This looks better! 👍

2022-06-27 14:31 UTC, live-wire approved these changes
Just tested this. 
LGTM

2022-06-27 18:47 UTC, merged