Job cancel should tear down within a reasonable amount of time
spotify/flink-on-k8s-operator pull request #443
Opened 2022-07-21 16:28 UTC by live-wire

2022-07-21 16:35 UTC, live-wire commented on apis/flinkcluster/v1beta1/flinkcluster_default.go
> +	ForceTearDownAfter         = time.Second * 10
This could be configured to slightly higher if necessary

2022-07-22 13:24 UTC, regadas requested changes
Hi @live-wire! Well I don't particularly fancy this solution tbh. The issues mentioned in #434 might actually be valid and I think from a first look that it's possible and worth tackling them differently.

I don't have time now but I can later today (next week) give more details / chat about this.

2022-07-22 13:27 UTC, live-wire commented
@regadas Sure. Let's sync on ways around it next week 👍

2022-07-25 11:06 UTC, live-wire commented
Hey @regadas 👋 
How do you want to go about it ? :)

2022-08-03 13:30 UTC, kassybas approved these changes
We can certainly improve and refactor based on the feedback from @regadas, however since this is often causes pods to be pending and not cancel, i think we should go ahead and merge.

2022-08-04 09:29 UTC, live-wire commented
Thanks @kassybas.
I agree. Merging this for now. 
I'll keep the original ticket open then. Please add the suggestions there @regadas 🙏

2022-08-04 09:29 UTC, merged