Sharder implementation MVP
spotify/flink-on-k8s-operator pull request #656
Opened 2023-03-20 19:23 UTC by live-wire

Things can get hairy when one operator pod is reconciling thousands of FlinkClusters. There is a flag to achieve concurrent reconciles: `max-concurrent-reconciles` but it is constrained by node memory (so this vertical scaling can only help you for so long).

This PR proposes a horizontal scaling solution for the flink operator. 
- This will make the operator use a `StatefulSet instead of a `Deployment` 
- `StatefulSet` has ordinal indexes in their pods and provides this guarantee: `Statefulsets have a guarantee that there will never be more than 1 instance of a pod at any given time`. This guarantee allows us to:
  - Sticky-shard workloads across the operator pods. (This PR contains a simple sharder implementation)
  - Not need leader election anymore, since there will only be one pod (per ordinal index) running at any given time.
- We don't need to worry about the webhooks since they already use a service and the webhook requests will be routed to one of the replicas (shards).

> NOTE: To make a release of this update, a delete + apply will be needed.

2023-03-21 07:56 UTC, regadas requested changes
Sharding is a good idea 👍. Left a few comments.

2023-03-21 07:56 UTC, regadas commented on config/manager/manager.yaml
> +    app: flink-operator
let's split this into a separate resource file.

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/flinkcluster_controller.go
> +	}
Instead of relying only on env vars, we should support arguments whose values can be set with env vars.

2023-03-21 07:56 UTC, regadas commented on config/manager/manager.yaml
> +            - name: SHARDS
we should rename this to `total-shards` to be clearer

2023-03-21 07:56 UTC, regadas commented on config/manager/manager.yaml
> +            - name: SHARD_NAME
let's also rename this to `pod` I foresee more usages for it.

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +	ShardId int // Shard ordinal for this instance
```suggestion
	TotalShards  int // Total number of shards
	Shard int // Shard ordinal for this instance
```

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +	ShardId int // Shard ordinal for this instance
:art: `ShardId` suggests smth else imo

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +	bigPrime := 31393
make it a `const`

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +	r, _ := regexp.Compile("(.*-)([0-9]+)$")
let's move this out ... no need to compile every time.

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +	}
make this a `func getShardFromPod`

2023-03-21 07:56 UTC, regadas commented on config/default/manager_config_patch.yaml
> +            - "--zap-log-level=info"
let's keep the default to be `error`

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/flinkcluster_controller.go
> +	log.Info("Reconciling FlinkCluster", "namespace", request.Namespace, "name", request.Name)
We have already a lot of logging with this info on the observer. We can skip.

2023-03-21 07:56 UTC, regadas commented on controllers/flinkcluster/sharder.go
> +func (s *Sharder) GetProcessorId(namespace, name string) int {
```suggestion
func (s *Sharder) GetShard(namespace, name string) int {
```

2023-03-21 08:09 UTC, regadas commented on controllers/flinkcluster/flinkcluster_controller.go
> +	}
Let's move this to `func Reconcile` avoiding passing it to the `handler`

2023-03-21 16:08 UTC, live-wire commented
Hey @regadas 
Made all the suggested changes 👍 
PTAL

2023-03-23 11:45 UTC, live-wire commented on config/default/manager_config_patch.yaml
> -kind: Deployment
HA + Leader election could still be used with StatefulSets. Using multiple replicas and passing in the enable leader election flag.

I'll add docs for it.

2023-04-05 10:19 UTC, merged